###user create

POST http://localhost:5000/user
Content-Type: application/json

{
    "first_name": "ruhul",
    "last_name": "amin",
    "user_name": "belayet",
    "password": "123456",
    "phone": "0169875893"
}
###get all user
GET http://localhost:5000/user

###get a user
GET http://localhost:5000/user/1

###Delete a user
DELETE  http://localhost:5000/user/1

###Login a user
POST http://localhost:5000/auth/login
Content-Type: application/json

{
    "user_name": "belayet",
    "password": "123456"
}